services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      sonarqube-db:
        condition: service_healthy
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=${SONAR_USER}
      - SONAR_JDBC_PASSWORD=${SONAR_PASSWORD}
    volumes:
      - ./data/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - ./data/sonarqube/sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarnet
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    restart: unless-stopped

  sonarqube-db:
    image: postgres:15.13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=${SONAR_USER}
      - POSTGRES_PASSWORD=${SONAR_PASSWORD}
      - POSTGRES_DB=sonarqube
    volumes:
      - ./data/sonarqube/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SONAR_USER} -d sonarqube"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 1g
    restart: unless-stopped

networks:
  sonarnet:
    driver: bridge
