services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.3
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always

volumes:
  open-webui:
