# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Profile:
  - website:
      - icon: si-aboutdotme
        href: https://jeerasakananta.dev
        description: Jeerasak Ananta personal website

  - LinkedIn:
      - icon: si-linkedin
        href: https://www.linkedin.com/in/jeerasakananta
        description: LinkedIn profile
        
- Repository:
    - GitHub:
        - icon: github-light.png
          href: https://github.com/jeerasakananta
          description: Code hosting platform

    - GitLab:
        - icon: gitlab.png
          href: https://gitlab.com/jeerasakananta
          description: DevOps platform  

    - Docker Hub:
        - icon: docker.png
          href: https://hub.docker.com/
          description: Container images

- Tools:
    - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com
          description: Cloudflare dashboard

   


    