---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Homelab Dashboard
favicon: homepage.png

theme: dark
color: slate

layout:
  Services:
    tab: Home
    style: row
    columns: 4

  Infrastructure:
    tab: Home
    style: row
    columns: 4

  CI/CD:
    tab: DevOps
    style: row
    columns: 4

  Development:
    tab: DevOps
    style: row
    columns: 4

  Monitoring & Logs:
    tab: Monitoring
    style: row
    columns: 4

  Storage:
    tab: Monitoring
    style: row
    columns: 4

headerStyle: boxed
statusStyle: dot
